Justin/wire sqlx access
GauravTalreja/ebb pull request #2
Opened 2023-05-24 22:13 UTC by Justin-Kwan

2023-05-24 22:26 UTC, Justin-Kwan commented on src/main.rs
> +                    PerseusRoot()
Do we know if the same context is automatically passed into all other components if we add the `CourseStore` object into `context` within this scope?

2023-05-25 06:25 UTC, GauravTalreja requested changes
Please re-request a review after making your changes, it should trigger a CI build.

2023-05-25 08:30 UTC, Justin-Kwan commented on src/backend/server.rs
> +        password: "password".to_string(),
@GauravTalreja Replace database password with actual. TODO: parse database config from toml file.

2023-05-25 08:31 UTC, Justin-Kwan commented on src/backend/storage/course_store.rs
> +        let fuzzy_search_pattern = ["%", course_name, "%"].concat();
Fuzzy searches courses by name.

2023-05-25 08:31 UTC, Justin-Kwan commented on src/backend/storage/mysql.rs
> +        let conn_pool = MySqlPoolOptions::new()
Establishes connection pool upfront against MySQL database.

2023-05-25 08:32 UTC, Justin-Kwan commented on src/config/reader.rs
> +pub fn read<T>(config_path: &Path) -> Result<T, ConfigError>
TODO: enable this method to read + parse toml config file given path passed into executable as argument.

2023-05-25 08:33 UTC, Justin-Kwan commented on src/templates/index.rs
> +    // TODO: fix api requests to backend endpoint for list of courses.
@GauravTalreja Here, we need to make a get request for list of courses to populate under the search bar. If you can TAL at why the requests are failing when made from localhost, that'd be great. (Requests to non-localhost URLs work correctly).

2023-05-25 08:40 UTC, Justin-Kwan commented
@GauravTalreja CI is green, feel free to TAL!

2023-05-27 20:34 UTC, GauravTalreja commented
Merged #3 based on this

2023-05-27 20:34 UTC, closed without merging